### ISSUE TITLE
What is the difference between SafetyHub12pts and SafetyHub17pts?

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd-starter-kit-config#2]
What is the difference between SafetyHub12pts and SafetyHub17pts? I don't know which one to use.

**Comment by GMezWheel** [comment]
SafetyHub12pts is the only valid commissioning files.
=> Safetyhub17pts is for futur specific SafetyHub.

**Comment by suguruhamada1003910** [comment]
Thank you for reply.

As for additional information, please see below.
https://github.com/ezWheelSAS/swd_ros_controllers/issues/46#issuecomment-1290047635
