### ISSUE TITLE
Safety fields default configuration

### ISSUE THREAD

**Issue by jkaniuka** [ezWheelSAS/swd-starter-kit-config#4]
I think there is a mistake in the [docs/Commissioning.md](https://github.com/ezWheelSAS/swd-starter-kit-config/blob/main/docs/Commissioning.md) file regarding **Protection zone 2** configuration where the SLS safety function is activated. In this file it is said that the safety function is activated when the obstacle is closer than 2 meters. According to the manual ( see image below) and based on tests with a real robot, this distance equals 1 meter. 

![image](https://github.com/ezWheelSAS/swd-starter-kit-config/assets/80155305/bf054c20-543c-4383-9dde-ace10fef728b)
_Image source:_ SWD Starter Kit Instruction manual V3 - 10/01/2023

**Comment by ez-Support** [comment]
Yes indeed you are right, thank you for pointing out the error.
We will fix it ASAP.

**Comment by jkaniuka** [comment]
Fixed in https://github.com/ezWheelSAS/swd-starter-kit-config/commit/88a577cbebc6f9eaaf7baf9d90e21bad3d6cef84
